name: Dependabot auto-merge
on:
  pull_request:
    types:
      - opened
      - reopened
      - edited

permissions:
  contents: write
  pull-requests: write

jobs:
  merge:
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' }}
    steps:
      - name: Fetch dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout
        id: checkout
        if: steps.metadata.outputs.update-type == 'version-update:semver-minor' || steps.metadata.outputs.update-type == 'version-update:semver-patch'
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: setup node
        id: node-setup
        if: steps.checkout.conclusion == 'success'
        uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc

      - name: Install dependencies
        id: update
        if: steps.node-setup.conclusion == 'success'
        run: npm ci --omit=dev

      - name: Commit dependencies
        id: commit
        if: steps.update.conclusion == 'success'
        run: |
          set -euo pipefail
          git config user.email "Sebastian.Goral@freenet.ag"
          git config user.name "Automatic dependency updates"
          git add node_modules
          git commit -m "Update node_modules after dependency update"
          git switch master
          git merge --squash "${{ github.head_ref }}"
